---
spring:
  profiles: subject
  application:
    name: subject-service
words: I,You,He,She,It
server:
  port: 8011

---
spring:
  profiles: verb
  application:
    name: verb-service
words: ran,knew,had,saw,bought
server:
  port: 8012
---
spring:
  profiles: article
  application:
    name: article-service
words: a,the
server:
  port: 8013
---
spring:
  profiles: adjective
  application:
    name: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8014
---
spring:
  profiles: noun
  application:
    name: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8015
---
spring:
  profiles: default
  application:
    name: default-service
words: default
server:
  port: 8016