---
spring:
  profiles: subject
words: I,You,He,She,It
server:
  port: 8011

---
spring:
  profiles: verb
  application:
    name: subject
words: ran,knew,had,saw,bought
server:
  port: 8012
---
spring:
  profiles: article
  application:
    name: article
words: a,the
server:
  port: 8013
---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8014
---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8015