---
spring:
  profiles: subject
  application:
    name: subject-service
words: I,You,He,She,It
server:
  port: 8021

---
spring:
  profiles: verb
  application:
    name: verb-service
words: ran,knew,had,saw,bought
server:
  port: 8022
---
spring:
  profiles: article
  application:
    name: article-service
words: a,the
server:
  port: 8023
---
spring:
  profiles: adjective
  application:
    name: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8024
---
spring:
  profiles: noun
  application:
    name: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8025
---
spring:
  profiles: default
  application:
    name: default-service
words: default,word,check
server:
  port: 8026
---
spring:
  profiles: cold-noun
  application:
    name: noun-service
words: icicle,refrigerator,blizzard,snowball
server:
  port: 8027